Repository vmware/dscr-for-vmware, pull requests merged in 2020-12, with the labels that each got.

#294 ConnectionFilter for vSphere Nodes
  Source/VMware.PSDesiredStateConfiguration/Classes/DscItems.ps1
  Source/VMware.PSDesiredStateConfiguration/Functions/Invoke-VmwDscConfiguration.ps1
  Source/VMware.PSDesiredStateConfiguration/Tests/Unit/Invoke-VmwDscConfiguration.tests.ps1
  VMware.PSDesiredStateConfiguration.md
Labels: enhancement, good first issue

#296 Fix bugs with physical network adapters when updating the teaming policy of the standard switch
  Source/VMware.vSphereDSC/DSCResources/StandardSwitch/VMHostVssTeaming.ps1
  Source/VMware.vSphereDSC/VMware.vSphereDSC.Helper.psm1
Labels: bug

#297 Move name validation to VmfsDatastore DSC Resource due to not being applicable for NfsDatastores
  Source/VMware.vSphereDSC/Classes/DatastoreBaseDSC.ps1
  Source/VMware.vSphereDSC/DSCResources/Datastore/VmfsDatastore.ps1
Labels: bug

#298 [Feature] IScsiName property of VMHostIScsiHba DSC Resource
  Documentation/DSCResources/VMHostIScsiHba/VMHostIScsiHba.md
  Source/VMware.vSphereDSC/Configurations/PowerShell/ESXiConfigs/VMHostIScsiHba/VMHostIScsiHba_ModifyIScsiNameOfIScsiHostBusAdapter_Config.ps1
  Source/VMware.vSphereDSC/DSCResources/VMHostIScsiHba.ps1
  Source/VMware.vSphereDSC/Tests/Integration/Configurations/VMHostIScsiHba/VMHostIScsiHba_Config.ps1
  Source/VMware.vSphereDSC/Tests/Integration/VMHostIScsiHba/VMHostIScsiHba.Integration.Tests.Helpers.ps1
  Source/VMware.vSphereDSC/Tests/Integration/VMHostIScsiHba/VMHostIScsiHba.Integration.Tests.ps1
  Source/VMware.vSphereDSC/Tests/Unit/TestHelpers/Mocks/MockData.ps1
  Source/VMware.vSphereDSC/Tests/Unit/TestHelpers/Mocks/VMHostIScsiHbaMocks.ps1
  Source/VMware.vSphereDSC/Tests/Unit/VMHostIScsiHba/VMHostIScsiHba.Unit.Tests.ps1
Labels: enhancement

#295 Print stream output from DSC Resources invoked by Invoke-DscResource
  Source/VMware.PSDesiredStateConfiguration/Classes/DscItems.ps1
  Source/VMware.PSDesiredStateConfiguration/VMware.PSDesiredStateConfiguration.build.ps1
  Source/VMware.PSDesiredStateConfiguration/VMware.PSDesiredStateConfiguration.psd1
  Source/VMware.vSphereDSC/Classes/BasevSphereConnection.ps1
  Source/VMware.vSphereDSC/Classes/DatastoreBaseDSC.ps1
  Source/VMware.vSphereDSC/Classes/VMHostEntityBaseDSC.ps1
  Source/VMware.vSphereDSC/Classes/VMHostNetworkMigrationBaseDSC.ps1
  Source/VMware.vSphereDSC/Classes/VMHostRestartBaseDSC.ps1
  Source/VMware.vSphereDSC/Classes/VMHostVssBaseDSC.ps1
  Source/VMware.vSphereDSC/DSCResources/DRSRule.ps1
  Source/VMware.vSphereDSC/DSCResources/Datastore/NfsDatastore.ps1
  Source/VMware.vSphereDSC/DSCResources/Datastore/VmfsDatastore.ps1
  Source/VMware.vSphereDSC/DSCResources/DatastoreCluster.ps1
  Source/VMware.vSphereDSC/DSCResources/DatastoreClusterAddDatastore.ps1
  Source/VMware.vSphereDSC/DSCResources/EsxCli/VMHostAcceptanceLevel.ps1
  Source/VMware.vSphereDSC/DSCResources/EsxCli/VMHostDCUIKeyboard.ps1
  Source/VMware.vSphereDSC/DSCResources/EsxCli/VMHostNetworkCoreDump.ps1
  Source/VMware.vSphereDSC/DSCResources/EsxCli/VMHostSNMPAgent.ps1
  Source/VMware.vSphereDSC/DSCResources/EsxCli/VMHostSharedSwapSpace.ps1
  Source/VMware.vSphereDSC/DSCResources/EsxCli/VMHostSoftwareDevice.ps1
  Source/VMware.vSphereDSC/DSCResources/EsxCli/VMHostVMKernelActiveDumpFile.ps1
  Source/VMware.vSphereDSC/DSCResources/EsxCli/VMHostVMKernelActiveDumpPartition.ps1
  Source/VMware.vSphereDSC/DSCResources/EsxCli/VMHostVMKernelDumpFile.ps1
  Source/VMware.vSphereDSC/DSCResources/EsxCli/VMHostVMKernelModule.ps1
  Source/VMware.vSphereDSC/DSCResources/EsxCli/VMHostvSANNetworkConfiguration.ps1
  Source/VMware.vSphereDSC/DSCResources/NfsUser.ps1
  Source/VMware.vSphereDSC/DSCResources/StandardSwitch/VMHostVss.ps1
  Source/VMware.vSphereDSC/DSCResources/StandardSwitch/VMHostVssBridge.ps1
  Source/VMware.vSphereDSC/DSCResources/StandardSwitch/VMHostVssSecurity.ps1
  Source/VMware.vSphereDSC/DSCResources/StandardSwitch/VMHostVssShaping.ps1
  Source/VMware.vSphereDSC/DSCResources/StandardSwitch/VMHostVssTeaming.ps1
  Source/VMware.vSphereDSC/DSCResources/VDSwitchVMHost.ps1
  Source/VMware.vSphereDSC/DSCResources/VMHostAccount.ps1
  Source/VMware.vSphereDSC/DSCResources/VMHostAdvancedSettings.ps1
  Source/VMware.vSphereDSC/DSCResources/VMHostAgentVM.ps1
  Source/VMware.vSphereDSC/DSCResources/VMHostCache.ps1
  Source/VMware.vSphereDSC/DSCResources/VMHostConfiguration.ps1
  Source/VMware.vSphereDSC/DSCResources/VMHostDnsSettings.ps1
  Source/VMware.vSphereDSC/DSCResources/VMHostFirewallRuleset.ps1
  Source/VMware.vSphereDSC/DSCResources/VMHostIScsiHba.ps1
  Source/VMware.vSphereDSC/DSCResources/VMHostIScsiHbaTarget.ps1
  Source/VMware.vSphereDSC/DSCResources/VMHostNetwork/VMHostIPRoute/VMHostIPRoute.ps1
  Source/VMware.vSphereDSC/DSCResources/VMHostNetwork/VMHostNetworkMigration/VMHostVDSwitchMigration.ps1
  Source/VMware.vSphereDSC/DSCResources/VMHostNetwork/VMHostNic/VMHostVdsNic.ps1
  Source/VMware.vSphereDSC/DSCResources/VMHostNtpSettings.ps1
  Source/VMware.vSphereDSC/DSCResources/VMHostPermission.ps1
  Source/VMware.vSphereDSC/DSCResources/VMHostRole.ps1
  Source/VMware.vSphereDSC/DSCResources/VMHostSatpClaimRule.ps1
  Source/VMware.vSphereDSC/DSCResources/VMHostScsiLun.ps1
  Source/VMware.vSphereDSC/DSCResources/VMHostScsiLunPath.ps1
  Source/VMware.vSphereDSC/DSCResources/VMHostService.ps1
  Source/VMware.vSphereDSC/DSCResources/VMHostSettings.ps1
  Source/VMware.vSphereDSC/DSCResources/VMHostSyslog.ps1
  Source/VMware.vSphereDSC/DSCResources/VMHostTpsSettings.ps1
  Source/VMware.vSphereDSC/DSCResources/vCenterSettings.ps1
  Source/VMware.vSphereDSC/DSCResources/vCenterStatistics.ps1
  Source/VMware.vSphereDSC/DSCResources/vCenterVMHost.ps1
  Source/VMware.vSphereDSC/VMware.vSphereDSC.Logging.psm1
Labels: enhancement, good first issue

#301 Fix the bug with the same references for DSC Resources when multiple vSphereNodes are passed as array in a DSC Configuration
  Source/VMware.PSDesiredStateConfiguration/Classes/DscItems.ps1
Labels: bug

#303 Integration Tests for VMware.PSDesiredStateConfiguration
  Source/VMware.PSDesiredStateConfiguration/Classes/DscItems.ps1
  Source/VMware.PSDesiredStateConfiguration/Tests/Integration/Configurations/vSphereNodeConfiguration.ps1
  Source/VMware.PSDesiredStateConfiguration/Tests/Integration/Invoke-VmwDscConfiguration.Integration.Tests.ps1
  Source/VMware.PSDesiredStateConfiguration/Tests/Integration/ServerConfig.ps1
Labels: enhancement
