Repository vmware/dscr-for-vmware, pull requests merged in 2020-09, with the labels that each got.

#275 Fixed bug of not exporting dsc resources and issue with Invoke-DscResource compatability (Fixes #263)
  Source/VMware.vSphereDSC/RequiredModules.ps1
  Source/VMware.vSphereDSC/VMware.vSphereDSC.psd1
Labels: bug

#276 Added fix for New-DscResourceBlock in CompositeResourcesHelper.ps1
  Source/VMware.vSphereDSC/DSCResources/Cluster/Cluster.schema.psm1
  Source/VMware.vSphereDSC/DSCResources/StandardPortGroup/StandardPortGroup.schema.psm1
  Source/VMware.vSphereDSC/DSCResources/StandardSwitch/StandardSwitch.schema.psm1
  Source/VMware.vSphereDSC/VMware.vSphereDSC.CompositeResourcesHelper.ps1
Labels: bug

#277 Fixed issue of comments getting duplicated after build process
  Source/VMware.vSphereDSC/RequiredModules.ps1
  Source/VMware.vSphereDSC/VMware.vSphereDSC.psd1
Labels: bug, build

#279 Fix bug with desired state when Account password should be changed
  Source/VMware.vSphereDSC/DSCResources/VMHostAccount.ps1
  Source/VMware.vSphereDSC/Tests/Unit/VMHostAccount.Unit.Tests.ps1
Labels: bug, dsc-resource
