Repository vmware/dscr-for-vmware, pull requests merged in 2021-01, with the labels that each got.

#299 Extend VMHostVDSwitchMigration DSC Resource to create distributed port groups with VLAN ID
  Source/VMware.vSphereDSC/DSCResources/VMHostNetwork/VMHostNetworkMigration/VMHostVDSwitchMigration.ps1
  Source/VMware.vSphereDSC/Tests/Integration/Configurations/VMHostVDSwitchMigration/VMHostVDSwitchMigration_Config.ps1
  Source/VMware.vSphereDSC/Tests/Integration/VMHostNetwork/VMHostNetworkMigration/VMHostVDSwitchMigration.Integration.Tests.ps1
  Source/VMware.vSphereDSC/Tests/Unit/TestHelpers/Mocks/MockData.ps1
  Source/VMware.vSphereDSC/Tests/Unit/TestHelpers/Mocks/VMHostVDSwitchMigrationMocks.ps1
  Source/VMware.vSphereDSC/Tests/Unit/VMHostNetwork/VMHostNetworkMigration/VMHostVDSwitchMigration.Unit.Tests.ps1
Labels: enhancement

#300 [Feature] VLanId property of VDPortGroup DSC Resource
  Documentation/DSCResources/VDPortGroup/VDPortGroup.md
  Source/VMware.vSphereDSC/Configurations/PowerShell/vCenterConfigs/VDPortGroup/VDPortGroup_CreateVDPortGroup_Config.ps1
  Source/VMware.vSphereDSC/DSCResources/VDPortGroup.ps1
  Source/VMware.vSphereDSC/Tests/Integration/Configurations/VDPortGroup/VDPortGroup_Config.ps1
  Source/VMware.vSphereDSC/Tests/Integration/VDPortGroup.Integration.Tests.ps1
  Source/VMware.vSphereDSC/Tests/Unit/TestHelpers/Mocks/MockData.ps1
  Source/VMware.vSphereDSC/Tests/Unit/TestHelpers/Mocks/VDPortGroupMocks.ps1
  Source/VMware.vSphereDSC/Tests/Unit/TestHelpers/VMware.VimAutomation.Core/PowerCLITypes.cs
  Source/VMware.vSphereDSC/Tests/Unit/TestHelpers/VMware.VimAutomation.Core/VMware.VimAutomation.Core.psm1
  Source/VMware.vSphereDSC/Tests/Unit/VDPortGroup.Unit.Tests.ps1
Labels: enhancement

#302 VMHostStorage DSC Resource
  Documentation/DSCResources/VMHostStorage/VMHostStorage.md
  Source/VMware.vSphereDSC/Configurations/PowerShell/ESXiConfigs/VMHostStorage/VMHostStorage_EnableSoftwareIscsi_Config.ps1
  Source/VMware.vSphereDSC/DSCResources/VMHostStorage.ps1
  Source/VMware.vSphereDSC/Tests/Integration/VMHostStorage/VMHostStorage.Integration.Tests.Helpers.ps1
  Source/VMware.vSphereDSC/Tests/Integration/VMHostStorage/VMHostStorage.Integration.Tests.ps1
  Source/VMware.vSphereDSC/Tests/Integration/VMHostStorage/VMHostStorage_Config.ps1
  Source/VMware.vSphereDSC/Tests/Unit/VMHostStorage/VMHostStorage.Mocks.Data.ps1
  Source/VMware.vSphereDSC/Tests/Unit/VMHostStorage/VMHostStorage.Mocks.ps1
  Source/VMware.vSphereDSC/Tests/Unit/VMHostStorage/VMHostStorage.Unit.Tests.ps1
Labels: dsc-resource, enhancement

#307 VMHostIScsiHbaVMKernelNic DSC Resource
  Documentation/DSCResources/VMHostIScsiHbaVMKernelNic/VMHostIScsiHbaVMKernelNic.md
  Source/VMware.vSphereDSC/Configurations/PowerShell/ESXiConfigs/VMHostIScsiHbaVMKernelNic/VMHostIScsiHbaVMKernelNic_BindVMKernelNicsToIscsiHba_Config.ps1
  Source/VMware.vSphereDSC/Configurations/PowerShell/ESXiConfigs/VMHostIScsiHbaVMKernelNic/VMHostIScsiHbaVMKernelNic_UnbindVMKernelNicsToIscsiHba_Config.ps1
  Source/VMware.vSphereDSC/DSCResources/VMHostIScsiHbaVMKernelNic.ps1
  Source/VMware.vSphereDSC/Tests/Integration/VMHostIScsiHbaVMKernelNic/VMHostIScsiHbaVMKernelNic.Integration.Tests.Helpers.ps1
  Source/VMware.vSphereDSC/Tests/Integration/VMHostIScsiHbaVMKernelNic/VMHostIScsiHbaVMKernelNic.Integration.Tests.ps1
  Source/VMware.vSphereDSC/Tests/Integration/VMHostIScsiHbaVMKernelNic/VMHostIScsiHbaVMKernelNic_Config.ps1
  Source/VMware.vSphereDSC/Tests/Unit/VMHostIScsiHbaVMKernelNic/VMHostIScsiHbaVMKernelNic.Mocks.Data.ps1
  Source/VMware.vSphereDSC/Tests/Unit/VMHostIScsiHbaVMKernelNic/VMHostIScsiHbaVMKernelNic.Mocks.ps1
  Source/VMware.vSphereDSC/Tests/Unit/VMHostIScsiHbaVMKernelNic/VMHostIScsiHbaVMKernelNic.Unit.Tests.ps1
  Source/VMware.vSphereDSC/VMware.vSphereDSC.Helper.psm1
Labels: dsc-resource, enhancement

#308 Add Getting Started sections for VMware.vSphereDSC and VMware.PSDesiredStateConfiguration
  README.md
Labels: documentation, enhancement, good first issue

#310 [Bug fixes] Exceptions not being thrown when invoking DSC Configurations through the VMware.PSDesiredStateConfiguration module
  Source/VMware.PSDesiredStateConfiguration/Classes/DscItems.ps1
  Source/VMware.PSDesiredStateConfiguration/VMware.PSDesiredStateConfiguration.psd1
  Source/VMware.vSphereDSC/Classes/BasevSphereConnection.ps1
  Source/VMware.vSphereDSC/Classes/VMHostGraphicsBaseDSC.ps1
  Source/VMware.vSphereDSC/Classes/VMHostNetworkBaseDSC.ps1
  Source/VMware.vSphereDSC/Classes/VMHostNicBaseDSC.ps1
  Source/VMware.vSphereDSC/Classes/VMHostVssPortGroupBaseDSC.ps1
  Source/VMware.vSphereDSC/Tests/Unit/BaseDSC.Unit.Tests.ps1
  Source/VMware.vSphereDSC/VMware.vSphereDSC.psd1
Labels: bug

#311 [Improvement] VMware.PSDesiredStateConfiguration verbose/error output improvement
  Source/VMware.PSDesiredStateConfiguration/Classes/DscItems.ps1
  Source/VMware.PSDesiredStateConfiguration/Functions/Errors.ps1
  Source/VMware.PSDesiredStateConfiguration/Functions/ExperimentalEnabled.ps1
  Source/VMware.PSDesiredStateConfiguration/Functions/Invoke-VmwDscConfiguration.ps1
  Source/VMware.PSDesiredStateConfiguration/Functions/KeyPropertyResourceCheckDotNet.ps1
  Source/VMware.PSDesiredStateConfiguration/Functions/New-VmwDscConfiguration.ps1
  Source/VMware.PSDesiredStateConfiguration/Tests/Integration/Configurations/vSphereNodeConfiguration.ps1
  Source/VMware.PSDesiredStateConfiguration/Tests/Integration/Invoke-VmwDscConfiguration.Integration.Tests.ps1
  Source/VMware.PSDesiredStateConfiguration/Tests/Integration/ServerConfig.ps1
  Source/VMware.PSDesiredStateConfiguration/Tests/Required Dsc Resources/MyDscResource/DSCResources/CompositeResourceTest/CompositeResourceTest.schema.psm1
  Source/VMware.PSDesiredStateConfiguration/Tests/Required Dsc Resources/MyDscResource/MyDscResource.psd1
  Source/VMware.PSDesiredStateConfiguration/Tests/Required Dsc Resources/MyDscResource/MyDscResource.psm1
  Source/VMware.PSDesiredStateConfiguration/Tests/Sample Configurations/Nodes/manyNodes.ps1
  Source/VMware.PSDesiredStateConfiguration/Tests/Sample Configurations/Nodes/oneNodeManyConnections.ps1
  Source/VMware.PSDesiredStateConfiguration/Tests/Sample Configurations/Nodes/singleNode.ps1
  Source/VMware.PSDesiredStateConfiguration/Tests/Sample Configurations/Nodes/singleNodeManyDefinitions.ps1
  Source/VMware.PSDesiredStateConfiguration/Tests/Sample Configurations/compositeResourceConfig.ps1
  Source/VMware.PSDesiredStateConfiguration/Tests/Sample Configurations/configParams.ps1
  Source/VMware.PSDesiredStateConfiguration/Tests/Sample Configurations/configurationDataConfig.ps1
  Source/VMware.PSDesiredStateConfiguration/Tests/Sample Configurations/dependsOnOrder.ps1
  Source/VMware.PSDesiredStateConfiguration/Tests/Sample Configurations/duplicateResources.ps1
  Source/VMware.PSDesiredStateConfiguration/Tests/Sample Configurations/fileParams.ps1
  Source/VMware.PSDesiredStateConfiguration/Tests/Sample Configurations/innerException.ps1
  Source/VMware.PSDesiredStateConfiguration/Tests/Sample Configurations/invalidDependsOn.ps1
  Source/VMware.PSDesiredStateConfiguration/Tests/Sample Configurations/manyResources.ps1
  Source/VMware.PSDesiredStateConfiguration/Tests/Sample Configurations/multipleDependsOnResource.ps1
  Source/VMware.PSDesiredStateConfiguration/Tests/Sample Configurations/nestedConfig.ps1
  Source/VMware.PSDesiredStateConfiguration/Tests/Sample Configurations/simple.ps1
  Source/VMware.PSDesiredStateConfiguration/Tests/Unit/Invoke-VmwDscConfiguration.tests.ps1
  Source/VMware.PSDesiredStateConfiguration/Tests/Unit/New-VmwDscConfiguration.tests.ps1
  Source/VMware.PSDesiredStateConfiguration/Tests/Utility.ps1
  Source/VMware.PSDesiredStateConfiguration/VMware.PSDesiredStateConfiguration.build.ps1
  Source/VMware.PSDesiredStateConfiguration/VMware.PSDesiredStateConfiguration.psd1
  Source/VMware.PSDesiredStateConfiguration/VMware.PSDesiredStateConfiguration.psm1
Labels: bug, build, enhancement

#314 [Bug fix] Extend key property validation with null check in VMware.PSDesiredStateConfiguration
  Source/VMware.PSDesiredStateConfiguration/Classes/DscItems.ps1
Labels: bug, dco-required
